### ISSUE TITLE
E_WARNING: Illegal string offset 'modified

### ISSUE THREAD

**Issue by whateverusernameisnottaken** [cosmocode/dokuwiki-plugin-publish#177]
Hi:

I'm pretty non-technical and don't understanding wikis/code.

For [FreshTomato Wiki](https://forum.dokuwiki.org/d/wiki.freshtomato.org)

the logs are showing a lot of entries similar to this:

2023-10-26 16:43:20
E_WARNING: Cannot modify header information - headers already sent by (output started at /home/fresoehv/wiki/lib/plugins/publish/helper.php:114)
/home/fresoehv/wiki/lib/tpl/mindthedark/main.php(12)
#0 [internal function]: dokuwiki\ErrorHandler::errorHandler(2, 'Cannot modify h...', '/home/fresoehv/...', 12, Array)
#1 /home/fresoehv/wiki/lib/tpl/mindthedark/main.php(12): header('X-UA-Compatible...')
#2 /home/fresoehv/wiki/inc/actions.php(27): include('/home/fresoehv/...')
#3 /home/fresoehv/wiki/doku.php(126): act_dispatch()
#4 {main}

We also get quite a few of these:

2023-10-26 16:22:14
E_WARNING: Illegal string offset 'modified'
/home/fresoehv/wiki/lib/plugins/publish/helper.php(114)
#0 /home/fresoehv/wiki/lib/plugins/publish/helper.php(114): dokuwiki\ErrorHandler::errorHandler(2, 'Illegal string ...', '/home/fresoehv/...', 114, Array)
#1 /home/fresoehv/wiki/lib/plugins/publish/helper.php(214): helper_plugin_publish->getRevision(NULL)
#2 /home/fresoehv/wiki/lib/plugins/publish/action/start.php(47): helper_plugin_publish->isCurrentRevisionApproved()
#3 /home/fresoehv/wiki/inc/Extension/EventHandler.php(80): action_plugin_publish_start->handle_start(Object(dokuwiki\Extension\Event), Array)
#4 /home/fresoehv/wiki/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
#5 /home/fresoehv/wiki/inc/Extension/Event.php(132): dokuwiki\Extension\Event->advise_before(false)
#6 /home/fresoehv/wiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger(NULL, false)
#7 /home/fresoehv/wiki/doku.php(120): dokuwiki\Extension\Event::createAndTrigger('DOKUWIKI_STARTE...', Array)

Can anyone help?

**Comment by whateverusernameisnottaken** [comment]
-CLOSING DUE TO BEING A DUPE-
